// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLrRAZsIICCMqp08c4PKNfQ30ROQKLf38',
    appId: '1:979684319326:web:01aca3a6faa8b26da6d4cf',
    messagingSenderId: '979684319326',
    projectId: 'heritageaskets',
    authDomain: 'heritageaskets.firebaseapp.com',
    storageBucket: 'heritageaskets.appspot.com',
    measurementId: 'G-6VJ2KT9K82',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0Ws-wCbL7r_Z4trfXwXm7mRc9ZQg7wdY',
    appId: '1:979684319326:android:e2591e260ae7dad0a6d4cf',
    messagingSenderId: '979684319326',
    projectId: 'heritageaskets',
    storageBucket: 'heritageaskets.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmdVMKFBZhovBhKq47dkVNEzS-RhGEGXE',
    appId: '1:979684319326:ios:f164ec3b0d7f1180a6d4cf',
    messagingSenderId: '979684319326',
    projectId: 'heritageaskets',
    storageBucket: 'heritageaskets.appspot.com',
    androidClientId: '979684319326-h3glkhke1j9m39cgms3gi7qblkabf42r.apps.googleusercontent.com',
    iosClientId: '979684319326-61le0jgqkums1lrorlhurhqlh1ls8729.apps.googleusercontent.com',
    iosBundleId: 'com.kologsoft.ecomoffice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmdVMKFBZhovBhKq47dkVNEzS-RhGEGXE',
    appId: '1:979684319326:ios:f164ec3b0d7f1180a6d4cf',
    messagingSenderId: '979684319326',
    projectId: 'heritageaskets',
    storageBucket: 'heritageaskets.appspot.com',
    androidClientId: '979684319326-h3glkhke1j9m39cgms3gi7qblkabf42r.apps.googleusercontent.com',
    iosClientId: '979684319326-61le0jgqkums1lrorlhurhqlh1ls8729.apps.googleusercontent.com',
    iosBundleId: 'com.kologsoft.ecomoffice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLrRAZsIICCMqp08c4PKNfQ30ROQKLf38',
    appId: '1:979684319326:web:01aca3a6faa8b26da6d4cf',
    messagingSenderId: '979684319326',
    projectId: 'heritageaskets',
    authDomain: 'heritageaskets.firebaseapp.com',
    storageBucket: 'heritageaskets.appspot.com',
    measurementId: 'G-6VJ2KT9K82',
  );

}